# Generated by Django 2.2.10 on 2020-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0046_auto_20200422_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_summon_dagger',
            field=models.BooleanField(default=False, help_text='Enable summon dagger tapping skill minigame.', verbose_name='Enable Summon Dagger'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='enable_forbidden_contract',
            field=models.BooleanField(default=False, help_text='Enable forbidden contract tapping skill minigame.', verbose_name='Enable Forbidden Contract'),
        ),
    ]
