# Generated by Django 2.2.10 on 2020-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titandash', '0049_remove_clan_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatistics',
            name='tournament_points',
            field=models.CharField(blank=True, help_text='How many overall tournaments points have been earned.', max_length=255, null=True, verbose_name='Tournament Points'),
        ),
    ]
