# Generated by Django 2.2.10 on 2020-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanbootstrap', '0002_remove_applicationsettings_tesseract_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
